version: '3.8'
services:
  gergich:
    image: instructure/gergich
    environment:
      - GERRIT_PATCHSET_REVISION
      - GERRIT_CHANGE_ID
      - GERGICH_KEY
      - GERRIT_PROJECT
      - GERRIT_HOST
      - GERRIT_BRANCH
    volumes:
      - .git:/app/.git:ro
      - coverage:/usr/src/app/coverage
      - tmp:/tmp
volumes:
  coverage:
  tmp:
